DELETE FROM zones_to_post_code_jp WHERE post_code = '9872265' AND zone_city_name = '栗原市' AND zone_street_name = '築館佐野原' AND zone_street_name_romaji = 'Tsukidate Sanohara';
DELETE FROM zones_to_post_code_jp WHERE post_code = '9813403' AND zone_city_name = '黒川郡大和町' AND zone_street_name = '落合檜和田' AND zone_street_name_romaji = 'Ochiai Hiwada';
DELETE FROM zones_to_post_code_jp WHERE post_code = '3900851' AND zone_city_name = '松本市' AND zone_street_name = '島内' AND zone_street_name_romaji = 'Shimauchi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '7596602' AND zone_city_name = '下関市' AND zone_street_name = '蒲生野' AND zone_street_name_romaji = 'Kamono';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5240202' AND zone_city_name = '野洲市' AND zone_street_name = '菖蒲' AND zone_street_name_romaji = 'Ayame';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5240203' AND zone_city_name = '野洲市' AND zone_street_name = '喜合' AND zone_street_name_romaji = 'Kigo';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5240201' AND zone_city_name = '野洲市' AND zone_street_name = '吉川' AND zone_street_name_romaji = 'Yoshikawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8830044' AND zone_city_name = '日向市' AND zone_street_name = '上町' AND zone_street_name_romaji = 'Uemachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8830043' AND zone_city_name = '日向市' AND zone_street_name = '都町' AND zone_street_name_romaji = 'Miyako Machi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '0530002' AND zone_city_name = '苫小牧市' AND zone_street_name = '晴海町' AND zone_street_name_romaji = 'Harumicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '0392823' AND zone_city_name = '上北郡七戸町' AND zone_street_name = '館ノ下' AND zone_street_name_romaji = 'Datenoshita';
DELETE FROM zones_to_post_code_jp WHERE post_code = '0392536' AND zone_city_name = '上北郡七戸町' AND zone_street_name = '野佐掛' AND zone_street_name_romaji = 'Nosakake';
DELETE FROM zones_to_post_code_jp WHERE post_code = '9893433' AND zone_city_name = '仙台市青葉区' AND zone_street_name = 'ニツカ' AND zone_street_name_romaji = 'Nikka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '2700162' AND zone_city_name = '流山市' AND zone_street_name = '木' AND zone_street_name_romaji = 'Ki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1500031' AND zone_city_name = '渋谷区' AND zone_street_name = '桜丘町' AND zone_street_name_romaji = 'Sakuragaoka Cho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8191601' AND zone_city_name = '糸島市' AND zone_street_name = '二丈深江' AND zone_street_name_romaji = 'Nijofukae';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8191612' AND zone_city_name = '糸島市' AND zone_street_name = '二丈松末' AND zone_street_name_romaji = 'Nijomasue';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8191613' AND zone_city_name = '糸島市' AND zone_street_name = '二丈松末' AND zone_street_name_romaji = 'Nijomasue';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8112312' AND zone_city_name = '糟屋郡粕屋町' AND zone_street_name = '戸原' AND zone_street_name_romaji = 'Tobara';
DELETE FROM zones_to_post_code_jp WHERE post_code = '2540012' AND zone_city_name = '平塚市' AND zone_street_name = '大神' AND zone_street_name_romaji = 'Okami';
DELETE FROM zones_to_post_code_jp WHERE post_code = '2540013' AND zone_city_name = '平塚市' AND zone_street_name = '田村' AND zone_street_name_romaji = 'Tamura';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4380025' AND zone_city_name = '磐田市' AND zone_street_name = '新貝' AND zone_street_name_romaji = 'Shingai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '6510068' AND zone_city_name = '神戸市中央区' AND zone_street_name = '旗塚通' AND zone_street_name_romaji = 'Hatatsukadori';
DELETE FROM zones_to_post_code_jp WHERE post_code = '6512213' AND zone_city_name = '神戸市西区' AND zone_street_name = '押部谷町福住' AND zone_street_name_romaji = 'Oshibedanicho Fukusumi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8100027' AND zone_city_name = '福岡市中央区' AND zone_street_name = '御所ケ谷' AND zone_street_name_romaji = 'Goshogadani';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8112416' AND zone_city_name = '糟屋郡篠栗町' AND zone_street_name = '田中' AND zone_street_name_romaji = 'Tanaka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '0883341' AND zone_city_name = '川上郡弟子屈町' AND zone_street_name = '屈斜路' AND zone_street_name_romaji = 'Kusshiyaro';
DELETE FROM zones_to_post_code_jp WHERE post_code = '0883341' AND zone_city_name = '川上郡弟子屈町' AND zone_street_name = '屈斜路原野' AND zone_street_name_romaji = 'Kusshiyarogenya';
DELETE FROM zones_to_post_code_jp WHERE post_code = '0883351' AND zone_city_name = '川上郡弟子屈町' AND zone_street_name = '屈斜路市街地' AND zone_street_name_romaji = 'Kusshiyaroshigaichi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '9650025' AND zone_city_name = '会津若松市' AND zone_street_name = '扇町' AND zone_street_name_romaji = 'Ogimachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '2892173' AND zone_city_name = '匝瑳市' AND zone_street_name = '飯高' AND zone_street_name_romaji = 'Iidaka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '2892176' AND zone_city_name = '匝瑳市' AND zone_street_name = '大堀' AND zone_street_name_romaji = 'Ohori';
DELETE FROM zones_to_post_code_jp WHERE post_code = '2892175' AND zone_city_name = '匝瑳市' AND zone_street_name = '片子' AND zone_street_name_romaji = 'Katako';
DELETE FROM zones_to_post_code_jp WHERE post_code = '2892156' AND zone_city_name = '匝瑳市' AND zone_street_name = '長岡' AND zone_street_name_romaji = 'Nagaoka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4320000' AND zone_city_name = '浜松市中区' AND zone_street_name = '' AND zone_street_name_romaji = '';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300805' AND zone_city_name = '浜松市中区' AND zone_street_name = '相生町' AND zone_street_name_romaji = 'Aioicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338111' AND zone_city_name = '浜松市中区' AND zone_street_name = '葵西' AND zone_street_name_romaji = 'Aoinishi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338114' AND zone_city_name = '浜松市中区' AND zone_street_name = '葵東' AND zone_street_name_romaji = 'Aoihigashi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328043' AND zone_city_name = '浜松市中区' AND zone_street_name = '浅田町' AND zone_street_name_romaji = 'Asadacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300927' AND zone_city_name = '浜松市中区' AND zone_street_name = '旭町' AND zone_street_name_romaji = 'Asahicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338113' AND zone_city_name = '浜松市中区' AND zone_street_name = '小豆餅' AND zone_street_name_romaji = 'Azukimochi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300945' AND zone_city_name = '浜松市中区' AND zone_street_name = '池町' AND zone_street_name_romaji = 'Ikemachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338124' AND zone_city_name = '浜松市中区' AND zone_street_name = '泉' AND zone_street_name_romaji = 'Izumi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338126' AND zone_city_name = '浜松市中区' AND zone_street_name = '泉町' AND zone_street_name_romaji = 'Izumicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300928' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町' AND zone_street_name_romaji = 'Itayamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307790' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（地階・階層不明）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(chikai.kaisofumei)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307701' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(1-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307702' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(2-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307703' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(3-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307704' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（４階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(4-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307705' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（５階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(5-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307706' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（６階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(6-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307707' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（７階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(7-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307708' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（８階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(8-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307709' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（９階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(9-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307710' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１０階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(10-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307711' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１１階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(11-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307712' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１２階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(12-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307713' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１３階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(13-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307714' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１４階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(14-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307715' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１５階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(15-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307716' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１６階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(16-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307717' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１７階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(17-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307718' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１８階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(18-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307719' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（１９階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(19-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307720' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２０階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(20-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307721' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２１階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(21-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307722' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２２階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(22-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307723' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２３階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(23-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307724' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２４階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(24-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307725' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２５階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(25-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307726' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２６階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(26-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307727' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２７階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(27-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307728' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２８階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(28-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307729' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（２９階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(29-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307730' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３０階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(30-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307731' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３１階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(31-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307732' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３２階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(32-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307733' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３３階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(33-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307734' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３４階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(34-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307735' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３５階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(35-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307736' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３６階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(36-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307737' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３７階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(37-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307738' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３８階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(38-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307739' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（３９階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(39-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307740' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（４０階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(40-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307741' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（４１階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(41-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307742' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（４２階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(42-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307743' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（４３階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(43-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307744' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（４４階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(44-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4307745' AND zone_city_name = '浜松市中区' AND zone_street_name = '板屋町浜松アクトタワー（４５階）' AND zone_street_name_romaji = 'Itayamachi Hamamatsuakutotawa(45-kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300854' AND zone_city_name = '浜松市中区' AND zone_street_name = '瓜内町' AND zone_street_name_romaji = 'Uriuchicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328033' AND zone_city_name = '浜松市中区' AND zone_street_name = '海老塚' AND zone_street_name_romaji = 'Ebitsuka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328032' AND zone_city_name = '浜松市中区' AND zone_street_name = '海老塚町' AND zone_street_name_romaji = 'Ebitsukacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300949' AND zone_city_name = '浜松市中区' AND zone_street_name = '尾張町' AND zone_street_name_romaji = 'Owaricho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300933' AND zone_city_name = '浜松市中区' AND zone_street_name = '鍛冶町' AND zone_street_name_romaji = 'Kajimachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328046' AND zone_city_name = '浜松市中区' AND zone_street_name = '春日町' AND zone_street_name_romaji = 'Kasugacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328042' AND zone_city_name = '浜松市中区' AND zone_street_name = '上浅田' AND zone_street_name_romaji = 'Kamiasada';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338122' AND zone_city_name = '浜松市中区' AND zone_street_name = '上島' AND zone_street_name_romaji = 'Kamijima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328047' AND zone_city_name = '浜松市中区' AND zone_street_name = '神田町' AND zone_street_name_romaji = 'Kamidamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328023' AND zone_city_name = '浜松市中区' AND zone_street_name = '鴨江' AND zone_street_name_romaji = 'Kamoe';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328024' AND zone_city_name = '浜松市中区' AND zone_street_name = '鴨江町' AND zone_street_name_romaji = 'Kamoecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300943' AND zone_city_name = '浜松市中区' AND zone_street_name = '北田町' AND zone_street_name_romaji = 'Kitatamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300923' AND zone_city_name = '浜松市中区' AND zone_street_name = '北寺島町' AND zone_street_name_romaji = 'Kitaterajimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300806' AND zone_city_name = '浜松市中区' AND zone_street_name = '木戸町' AND zone_street_name_romaji = 'Kidocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300948' AND zone_city_name = '浜松市中区' AND zone_street_name = '元目町' AND zone_street_name_romaji = 'Genmokucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300938' AND zone_city_name = '浜松市中区' AND zone_street_name = '紺屋町' AND zone_street_name_romaji = 'Koyamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338123' AND zone_city_name = '浜松市中区' AND zone_street_name = '幸' AND zone_street_name_romaji = 'Saiwai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328025' AND zone_city_name = '浜松市中区' AND zone_street_name = '栄町' AND zone_street_name_romaji = 'Sakaemachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300932' AND zone_city_name = '浜松市中区' AND zone_street_name = '肴町' AND zone_street_name_romaji = 'Sakanamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300807' AND zone_city_name = '浜松市中区' AND zone_street_name = '佐藤' AND zone_street_name_romaji = 'Sato';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328021' AND zone_city_name = '浜松市中区' AND zone_street_name = '佐鳴台' AND zone_street_name_romaji = 'Sanarudai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328034' AND zone_city_name = '浜松市中区' AND zone_street_name = '塩町' AND zone_street_name_romaji = 'Shiomachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328014' AND zone_city_name = '浜松市中区' AND zone_street_name = '鹿谷町' AND zone_street_name_romaji = 'Shikatanicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328018' AND zone_city_name = '浜松市中区' AND zone_street_name = '蜆塚' AND zone_street_name_romaji = 'Shijimizuka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350055' AND zone_city_name = '浜松市中区' AND zone_street_name = '十軒町' AND zone_street_name_romaji = 'Jikkencho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300905' AND zone_city_name = '浜松市中区' AND zone_street_name = '下池川町' AND zone_street_name_romaji = 'Shimoikegawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328011' AND zone_city_name = '浜松市中区' AND zone_street_name = '城北' AND zone_street_name_romaji = 'Johoku';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300911' AND zone_city_name = '浜松市中区' AND zone_street_name = '新津町' AND zone_street_name_romaji = 'Shinzucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300931' AND zone_city_name = '浜松市中区' AND zone_street_name = '神明町' AND zone_street_name_romaji = 'Shinmeicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328041' AND zone_city_name = '浜松市中区' AND zone_street_name = '菅原町' AND zone_street_name_romaji = 'Sugawaracho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300903' AND zone_city_name = '浜松市中区' AND zone_street_name = '助信町' AND zone_street_name_romaji = 'Sukenobucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300926' AND zone_city_name = '浜松市中区' AND zone_street_name = '砂山町' AND zone_street_name_romaji = 'Sunayamacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300906' AND zone_city_name = '浜松市中区' AND zone_street_name = '住吉' AND zone_street_name_romaji = 'Sumiyoshi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350054' AND zone_city_name = '浜松市中区' AND zone_street_name = '早出町' AND zone_street_name_romaji = 'Sodecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300936' AND zone_city_name = '浜松市中区' AND zone_street_name = '大工町' AND zone_street_name_romaji = 'Daikumachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338119' AND zone_city_name = '浜松市中区' AND zone_street_name = '高丘北' AND zone_street_name_romaji = 'Takaokakita';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338118' AND zone_city_name = '浜松市中区' AND zone_street_name = '高丘西' AND zone_street_name_romaji = 'Takaokanishi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338117' AND zone_city_name = '浜松市中区' AND zone_street_name = '高丘東' AND zone_street_name_romaji = 'Takaokahigashi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300907' AND zone_city_name = '浜松市中区' AND zone_street_name = '高林' AND zone_street_name_romaji = 'Takabayashi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328015' AND zone_city_name = '浜松市中区' AND zone_street_name = '高町' AND zone_street_name_romaji = 'Takamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300944' AND zone_city_name = '浜松市中区' AND zone_street_name = '田町' AND zone_street_name_romaji = 'Tamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300934' AND zone_city_name = '浜松市中区' AND zone_street_name = '千歳町' AND zone_street_name_romaji = 'Chitosecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300929' AND zone_city_name = '浜松市中区' AND zone_street_name = '中央' AND zone_street_name_romaji = 'Chuo';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300925' AND zone_city_name = '浜松市中区' AND zone_street_name = '寺島町' AND zone_street_name_romaji = 'Terajimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300808' AND zone_city_name = '浜松市中区' AND zone_street_name = '天神町' AND zone_street_name_romaji = 'Tenjinmachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300935' AND zone_city_name = '浜松市中区' AND zone_street_name = '伝馬町' AND zone_street_name_romaji = 'Tenmacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300937' AND zone_city_name = '浜松市中区' AND zone_street_name = '利町' AND zone_street_name_romaji = 'Togimachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300917' AND zone_city_name = '浜松市中区' AND zone_street_name = '常盤町' AND zone_street_name_romaji = 'Tokiwacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328002' AND zone_city_name = '浜松市中区' AND zone_street_name = '富塚町' AND zone_street_name_romaji = 'Tomitsukacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300804' AND zone_city_name = '浜松市中区' AND zone_street_name = '富吉町' AND zone_street_name_romaji = 'Tomiyoshicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300904' AND zone_city_name = '浜松市中区' AND zone_street_name = '中沢町' AND zone_street_name_romaji = 'Nakazawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300856' AND zone_city_name = '浜松市中区' AND zone_street_name = '中島' AND zone_street_name_romaji = 'Nakajima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300857' AND zone_city_name = '浜松市中区' AND zone_street_name = '中島町' AND zone_street_name_romaji = 'Nakajimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328016' AND zone_city_name = '浜松市中区' AND zone_street_name = '中山町' AND zone_street_name_romaji = 'Nakayamacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300912' AND zone_city_name = '浜松市中区' AND zone_street_name = '茄子町' AND zone_street_name_romaji = 'Nasubicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300811' AND zone_city_name = '浜松市中区' AND zone_street_name = '名塚町' AND zone_street_name_romaji = 'Nazukacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328031' AND zone_city_name = '浜松市中区' AND zone_street_name = '平田町' AND zone_street_name_romaji = 'Namedacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328035' AND zone_city_name = '浜松市中区' AND zone_street_name = '成子町' AND zone_street_name_romaji = 'Narukocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328045' AND zone_city_name = '浜松市中区' AND zone_street_name = '西浅田' AND zone_street_name_romaji = 'Nishiasada';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328038' AND zone_city_name = '浜松市中区' AND zone_street_name = '西伊場町' AND zone_street_name_romaji = 'Nishiibacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338116' AND zone_city_name = '浜松市中区' AND zone_street_name = '西丘町' AND zone_street_name_romaji = 'Nishiokacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328012' AND zone_city_name = '浜松市中区' AND zone_street_name = '布橋' AND zone_street_name_romaji = 'Nunohashi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300919' AND zone_city_name = '浜松市中区' AND zone_street_name = '野口町' AND zone_street_name_romaji = 'Noguchicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328053' AND zone_city_name = '浜松市中区' AND zone_street_name = '法枝町' AND zone_street_name_romaji = 'Noriedacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338121' AND zone_city_name = '浜松市中区' AND zone_street_name = '萩丘' AND zone_street_name_romaji = 'Hagioka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328027' AND zone_city_name = '浜松市中区' AND zone_street_name = '旅籠町' AND zone_street_name_romaji = 'Hatagomachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300918' AND zone_city_name = '浜松市中区' AND zone_street_name = '八幡町' AND zone_street_name_romaji = 'Hachimancho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338109' AND zone_city_name = '浜松市中区' AND zone_street_name = '花川町' AND zone_street_name_romaji = 'Hanakawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300916' AND zone_city_name = '浜松市中区' AND zone_street_name = '早馬町' AND zone_street_name_romaji = 'Hayaumacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328036' AND zone_city_name = '浜松市中区' AND zone_street_name = '東伊場' AND zone_street_name_romaji = 'Higashiiba';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300915' AND zone_city_name = '浜松市中区' AND zone_street_name = '東田町' AND zone_street_name_romaji = 'Higashitamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300901' AND zone_city_name = '浜松市中区' AND zone_street_name = '曳馬' AND zone_street_name_romaji = 'Hikuma';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300902' AND zone_city_name = '浜松市中区' AND zone_street_name = '曳馬町' AND zone_street_name_romaji = 'Hikumacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328013' AND zone_city_name = '浜松市中区' AND zone_street_name = '広沢' AND zone_street_name_romaji = 'Hirosawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300913' AND zone_city_name = '浜松市中区' AND zone_street_name = '船越町' AND zone_street_name_romaji = 'Funakoshicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328004' AND zone_city_name = '浜松市中区' AND zone_street_name = '文丘町' AND zone_street_name_romaji = 'Fumiokacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350045' AND zone_city_name = '浜松市中区' AND zone_street_name = '細島町' AND zone_street_name_romaji = 'Hosojimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300947' AND zone_city_name = '浜松市中区' AND zone_street_name = '松城町' AND zone_street_name_romaji = 'Matsushirocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328017' AND zone_city_name = '浜松市中区' AND zone_street_name = '三組町' AND zone_street_name_romaji = 'Mikumicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328044' AND zone_city_name = '浜松市中区' AND zone_street_name = '南浅田' AND zone_street_name_romaji = 'Minamiasada';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328037' AND zone_city_name = '浜松市中区' AND zone_street_name = '南伊場町' AND zone_street_name_romaji = 'Minamiibacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300851' AND zone_city_name = '浜松市中区' AND zone_street_name = '向宿' AND zone_street_name_romaji = 'Mukojuku';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328026' AND zone_city_name = '浜松市中区' AND zone_street_name = '元魚町' AND zone_street_name_romaji = 'Motocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300946' AND zone_city_name = '浜松市中区' AND zone_street_name = '元城町' AND zone_street_name_romaji = 'Motoshirocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300942' AND zone_city_name = '浜松市中区' AND zone_street_name = '元浜町' AND zone_street_name_romaji = 'Motohamacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328048' AND zone_city_name = '浜松市中区' AND zone_street_name = '森田町' AND zone_street_name_romaji = 'Moritacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300941' AND zone_city_name = '浜松市中区' AND zone_street_name = '山下町' AND zone_street_name_romaji = 'Yamashitacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328022' AND zone_city_name = '浜松市中区' AND zone_street_name = '山手町' AND zone_street_name_romaji = 'Yamatecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300924' AND zone_city_name = '浜松市中区' AND zone_street_name = '龍禅寺町' AND zone_street_name_romaji = 'Ryuzenjicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300852' AND zone_city_name = '浜松市中区' AND zone_street_name = '領家' AND zone_street_name_romaji = 'Ryoke';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300939' AND zone_city_name = '浜松市中区' AND zone_street_name = '連尺町' AND zone_street_name_romaji = 'Renjakucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338127' AND zone_city_name = '浜松市中区' AND zone_street_name = '和合北' AND zone_street_name_romaji = 'Wagokita';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338125' AND zone_city_name = '浜松市中区' AND zone_street_name = '和合町' AND zone_street_name_romaji = 'Wagocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328003' AND zone_city_name = '浜松市中区' AND zone_street_name = '和地山' AND zone_street_name_romaji = 'Wajiyama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4320000' AND zone_city_name = '浜松市東区' AND zone_street_name = '' AND zone_street_name_romaji = '';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313121' AND zone_city_name = '浜松市東区' AND zone_street_name = '有玉北町' AND zone_street_name_romaji = 'Aritama Kitamachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313126' AND zone_city_name = '浜松市東区' AND zone_street_name = '有玉台' AND zone_street_name_romaji = 'Aritamadai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313123' AND zone_city_name = '浜松市東区' AND zone_street_name = '有玉西町' AND zone_street_name_romaji = 'Aritama Nishimachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313122' AND zone_city_name = '浜松市東区' AND zone_street_name = '有玉南町' AND zone_street_name_romaji = 'Aritama Minamimachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350005' AND zone_city_name = '浜松市東区' AND zone_street_name = '安新町' AND zone_street_name_romaji = 'Anshincho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350012' AND zone_city_name = '浜松市東区' AND zone_street_name = '安間町' AND zone_street_name_romaji = 'Anmacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350051' AND zone_city_name = '浜松市東区' AND zone_street_name = '市野町' AND zone_street_name_romaji = 'Ichinocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300803' AND zone_city_name = '浜松市東区' AND zone_street_name = '植松町' AND zone_street_name_romaji = 'Uematsucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350014' AND zone_city_name = '浜松市東区' AND zone_street_name = '大蒲町' AND zone_street_name_romaji = 'Okabacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313112' AND zone_city_name = '浜松市東区' AND zone_street_name = '大島町' AND zone_street_name_romaji = 'Oshimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313113' AND zone_city_name = '浜松市東区' AND zone_street_name = '大瀬町' AND zone_street_name_romaji = 'Osecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313106' AND zone_city_name = '浜松市東区' AND zone_street_name = '笠井上町' AND zone_street_name_romaji = 'Kasai Kamimachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313105' AND zone_city_name = '浜松市東区' AND zone_street_name = '笠井新田町' AND zone_street_name_romaji = 'Kasai Shindencho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313107' AND zone_city_name = '浜松市東区' AND zone_street_name = '笠井町' AND zone_street_name_romaji = 'Kasaicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350053' AND zone_city_name = '浜松市東区' AND zone_street_name = '上新屋町' AND zone_street_name_romaji = 'Kamiarayacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350001' AND zone_city_name = '浜松市東区' AND zone_street_name = '上石田町' AND zone_street_name_romaji = 'Kamiishidacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350048' AND zone_city_name = '浜松市東区' AND zone_street_name = '上西町' AND zone_street_name_romaji = 'Kaminishicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350041' AND zone_city_name = '浜松市東区' AND zone_street_name = '北島町' AND zone_street_name_romaji = 'Kitajimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313104' AND zone_city_name = '浜松市東区' AND zone_street_name = '貴平町' AND zone_street_name_romaji = 'Kiheicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350011' AND zone_city_name = '浜松市東区' AND zone_street_name = '国吉町' AND zone_street_name_romaji = 'Kuniyoshicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350056' AND zone_city_name = '浜松市東区' AND zone_street_name = '小池町' AND zone_street_name_romaji = 'Koikecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300801' AND zone_city_name = '浜松市東区' AND zone_street_name = '神立町' AND zone_street_name_romaji = 'Kodachicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350015' AND zone_city_name = '浜松市東区' AND zone_street_name = '子安町' AND zone_street_name_romaji = 'Koyasucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350021' AND zone_city_name = '浜松市東区' AND zone_street_name = '材木町' AND zone_street_name_romaji = 'Zaimokucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350042' AND zone_city_name = '浜松市東区' AND zone_street_name = '篠ケ瀬町' AND zone_street_name_romaji = 'Sasagasecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350006' AND zone_city_name = '浜松市東区' AND zone_street_name = '下石田町' AND zone_street_name_romaji = 'Shimoishidacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300802' AND zone_city_name = '浜松市東区' AND zone_street_name = '将監町' AND zone_street_name_romaji = 'Shogencho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313103' AND zone_city_name = '浜松市東区' AND zone_street_name = '常光町' AND zone_street_name_romaji = 'Jokocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350002' AND zone_city_name = '浜松市東区' AND zone_street_name = '白鳥町' AND zone_street_name_romaji = 'Shirotoricho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313114' AND zone_city_name = '浜松市東区' AND zone_street_name = '積志町' AND zone_street_name_romaji = 'Sekishicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313108' AND zone_city_name = '浜松市東区' AND zone_street_name = '恒武町' AND zone_street_name_romaji = 'Tsunetakecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350052' AND zone_city_name = '浜松市東区' AND zone_street_name = '天王町' AND zone_street_name_romaji = 'Tennocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350013' AND zone_city_name = '浜松市東区' AND zone_street_name = '天龍川町' AND zone_street_name_romaji = 'Tenryugawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313102' AND zone_city_name = '浜松市東区' AND zone_street_name = '豊西町' AND zone_street_name_romaji = 'Toyonishicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313111' AND zone_city_name = '浜松市東区' AND zone_street_name = '中郡町' AND zone_street_name_romaji = 'Nakagoricho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350003' AND zone_city_name = '浜松市東区' AND zone_street_name = '中里町' AND zone_street_name_romaji = 'Nakasatocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350057' AND zone_city_name = '浜松市東区' AND zone_street_name = '中田町' AND zone_street_name_romaji = 'Nakadacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350031' AND zone_city_name = '浜松市東区' AND zone_street_name = '長鶴町' AND zone_street_name_romaji = 'Nagatsurucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350004' AND zone_city_name = '浜松市東区' AND zone_street_name = '中野町' AND zone_street_name_romaji = 'Nakanomachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313115' AND zone_city_name = '浜松市東区' AND zone_street_name = '西ケ崎町' AND zone_street_name_romaji = 'Nishigasakicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350044' AND zone_city_name = '浜松市東区' AND zone_street_name = '西塚町' AND zone_street_name_romaji = 'Nishizukacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350047' AND zone_city_name = '浜松市東区' AND zone_street_name = '原島町' AND zone_street_name_romaji = 'Barajimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313124' AND zone_city_name = '浜松市東区' AND zone_street_name = '半田町' AND zone_street_name_romaji = 'Handacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313125' AND zone_city_name = '浜松市東区' AND zone_street_name = '半田山' AND zone_street_name_romaji = 'Handayama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350008' AND zone_city_name = '浜松市東区' AND zone_street_name = '松小池町' AND zone_street_name_romaji = 'Matsukoikecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350046' AND zone_city_name = '浜松市東区' AND zone_street_name = '丸塚町' AND zone_street_name_romaji = 'Maruzukacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350043' AND zone_city_name = '浜松市東区' AND zone_street_name = '宮竹町' AND zone_street_name_romaji = 'Miyatakecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350017' AND zone_city_name = '浜松市東区' AND zone_street_name = '薬師町' AND zone_street_name_romaji = 'Yakushicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350018' AND zone_city_name = '浜松市東区' AND zone_street_name = '薬新町' AND zone_street_name_romaji = 'Yakushincho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313101' AND zone_city_name = '浜松市東区' AND zone_street_name = '豊町' AND zone_street_name_romaji = 'Yutakacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350029' AND zone_city_name = '浜松市東区' AND zone_street_name = '龍光町' AND zone_street_name_romaji = 'Ryukocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350007' AND zone_city_name = '浜松市東区' AND zone_street_name = '流通元町' AND zone_street_name_romaji = 'Ryutsumotomachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350016' AND zone_city_name = '浜松市東区' AND zone_street_name = '和田町' AND zone_street_name_romaji = 'Wadacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4320000' AND zone_city_name = '浜松市西区' AND zone_street_name = '' AND zone_street_name_romaji = '';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311111' AND zone_city_name = '浜松市西区' AND zone_street_name = '伊左地町' AND zone_street_name_romaji = 'Isajicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328061' AND zone_city_name = '浜松市西区' AND zone_street_name = '入野町' AND zone_street_name_romaji = 'Irinocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328006' AND zone_city_name = '浜松市西区' AND zone_street_name = '大久保町' AND zone_street_name_romaji = 'Okubocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311112' AND zone_city_name = '浜松市西区' AND zone_street_name = '大人見町' AND zone_street_name_romaji = 'Ohitomicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328068' AND zone_city_name = '浜松市西区' AND zone_street_name = '大平台' AND zone_street_name_romaji = 'Ohiradai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311102' AND zone_city_name = '浜松市西区' AND zone_street_name = '大山町' AND zone_street_name_romaji = 'Oyamacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328005' AND zone_city_name = '浜松市西区' AND zone_street_name = '神ケ谷町' AND zone_street_name_romaji = 'Kamigayacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328007' AND zone_city_name = '浜松市西区' AND zone_street_name = '神原町' AND zone_street_name_romaji = 'Kamiharacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311209' AND zone_city_name = '浜松市西区' AND zone_street_name = '舘山寺町' AND zone_street_name_romaji = 'Kanzanjicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311205' AND zone_city_name = '浜松市西区' AND zone_street_name = '協和町' AND zone_street_name_romaji = 'Kyowacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311202' AND zone_city_name = '浜松市西区' AND zone_street_name = '呉松町' AND zone_street_name_romaji = 'Kurematsucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311103' AND zone_city_name = '浜松市西区' AND zone_street_name = '湖東町' AND zone_street_name_romaji = 'Kotocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311113' AND zone_city_name = '浜松市西区' AND zone_street_name = '古人見町' AND zone_street_name_romaji = 'Kohitomicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311104' AND zone_city_name = '浜松市西区' AND zone_street_name = '桜台' AND zone_street_name_romaji = 'Sakuradai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311114' AND zone_city_name = '浜松市西区' AND zone_street_name = '佐浜町' AND zone_street_name_romaji = 'Sahamacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328069' AND zone_city_name = '浜松市西区' AND zone_street_name = '志都呂' AND zone_street_name_romaji = 'Shitoro';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328066' AND zone_city_name = '浜松市西区' AND zone_street_name = '志都呂町' AND zone_street_name_romaji = 'Shitorocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310201' AND zone_city_name = '浜松市西区' AND zone_street_name = '篠原町' AND zone_street_name_romaji = 'Shinoharacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311208' AND zone_city_name = '浜松市西区' AND zone_street_name = '庄内町' AND zone_street_name_romaji = 'Shonaicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311206' AND zone_city_name = '浜松市西区' AND zone_street_name = '庄和町' AND zone_street_name_romaji = 'Showacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311204' AND zone_city_name = '浜松市西区' AND zone_street_name = '白洲町' AND zone_street_name_romaji = 'Shirasucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328071' AND zone_city_name = '浜松市西区' AND zone_street_name = '西都台町' AND zone_street_name_romaji = 'Seitodaicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310202' AND zone_city_name = '浜松市西区' AND zone_street_name = '坪井町' AND zone_street_name_romaji = 'Tsuboicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328067' AND zone_city_name = '浜松市西区' AND zone_street_name = '西鴨江町' AND zone_street_name_romaji = 'Nishikamoecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328001' AND zone_city_name = '浜松市西区' AND zone_street_name = '西山町' AND zone_street_name_romaji = 'Nishiyamacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311203' AND zone_city_name = '浜松市西区' AND zone_street_name = '平松町' AND zone_street_name_romaji = 'Hiramatsucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311201' AND zone_city_name = '浜松市西区' AND zone_street_name = '深萩町' AND zone_street_name_romaji = 'Fukahagicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310212' AND zone_city_name = '浜松市西区' AND zone_street_name = '舞阪町長十新田' AND zone_street_name_romaji = 'Maisakacho Chojushinden';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310213' AND zone_city_name = '浜松市西区' AND zone_street_name = '舞阪町浜田' AND zone_street_name_romaji = 'Maisakacho Hamada';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310214' AND zone_city_name = '浜松市西区' AND zone_street_name = '舞阪町弁天島' AND zone_street_name_romaji = 'Maisakacho Bentenjima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310211' AND zone_city_name = '浜松市西区' AND zone_street_name = '舞阪町舞阪' AND zone_street_name_romaji = 'Maisakacho Maisaka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310203' AND zone_city_name = '浜松市西区' AND zone_street_name = '馬郡町' AND zone_street_name_romaji = 'Magoricho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311207' AND zone_city_name = '浜松市西区' AND zone_street_name = '村櫛町' AND zone_street_name_romaji = 'Murakushicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310103' AND zone_city_name = '浜松市西区' AND zone_street_name = '雄踏' AND zone_street_name_romaji = 'Yuto';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310102' AND zone_city_name = '浜松市西区' AND zone_street_name = '雄踏町宇布見' AND zone_street_name_romaji = 'Yutocho Ubumi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4310101' AND zone_city_name = '浜松市西区' AND zone_street_name = '雄踏町山崎' AND zone_street_name_romaji = 'Yutocho Yamazaki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311101' AND zone_city_name = '浜松市西区' AND zone_street_name = '和光町' AND zone_street_name_romaji = 'Wakocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311115' AND zone_city_name = '浜松市西区' AND zone_street_name = '和地町' AND zone_street_name_romaji = 'Wajicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4320000' AND zone_city_name = '浜松市南区' AND zone_street_name = '' AND zone_street_name_romaji = '';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350037' AND zone_city_name = '浜松市南区' AND zone_street_name = '青屋町' AND zone_street_name_romaji = 'Aoyacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350028' AND zone_city_name = '浜松市南区' AND zone_street_name = '飯田町' AND zone_street_name_romaji = 'Iidacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350033' AND zone_city_name = '浜松市南区' AND zone_street_name = '石原町' AND zone_street_name_romaji = 'Ishiharacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300854' AND zone_city_name = '浜松市南区' AND zone_street_name = '瓜内町' AND zone_street_name_romaji = 'Uriuchicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300844' AND zone_city_name = '浜松市南区' AND zone_street_name = '江之島町' AND zone_street_name_romaji = 'Enoshimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300835' AND zone_city_name = '浜松市南区' AND zone_street_name = '遠州浜' AND zone_street_name_romaji = 'Enshuhama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350025' AND zone_city_name = '浜松市南区' AND zone_street_name = '老間町' AND zone_street_name_romaji = 'Oimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350024' AND zone_city_name = '浜松市南区' AND zone_street_name = '大塚町' AND zone_street_name_romaji = 'Otsukacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300842' AND zone_city_name = '浜松市南区' AND zone_street_name = '大柳町' AND zone_street_name_romaji = 'Oyagicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328055' AND zone_city_name = '浜松市南区' AND zone_street_name = '卸本町' AND zone_street_name_romaji = 'Oroshihonmachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300814' AND zone_city_name = '浜松市南区' AND zone_street_name = '恩地町' AND zone_street_name_romaji = 'Onjicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350026' AND zone_city_name = '浜松市南区' AND zone_street_name = '金折町' AND zone_street_name_romaji = 'Kanaoricho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300823' AND zone_city_name = '浜松市南区' AND zone_street_name = '河輪町' AND zone_street_name_romaji = 'Kawawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328064' AND zone_city_name = '浜松市南区' AND zone_street_name = '倉松町' AND zone_street_name_romaji = 'Kuramatsucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300831' AND zone_city_name = '浜松市南区' AND zone_street_name = '御給町' AND zone_street_name_romaji = 'Gokyucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328063' AND zone_city_name = '浜松市南区' AND zone_street_name = '小沢渡町' AND zone_street_name_romaji = 'Kozawataricho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300816' AND zone_city_name = '浜松市南区' AND zone_street_name = '参野町' AND zone_street_name_romaji = 'Sanjinocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300833' AND zone_city_name = '浜松市南区' AND zone_street_name = '三新町' AND zone_street_name_romaji = 'Sanshincho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350038' AND zone_city_name = '浜松市南区' AND zone_street_name = '三和町' AND zone_street_name_romaji = 'Sanwacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300826' AND zone_city_name = '浜松市南区' AND zone_street_name = '四本松町' AND zone_street_name_romaji = 'Shihonmatsucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350027' AND zone_city_name = '浜松市南区' AND zone_street_name = '下飯田町' AND zone_street_name_romaji = 'Shimoiidacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300825' AND zone_city_name = '浜松市南区' AND zone_street_name = '下江町' AND zone_street_name_romaji = 'Shimoecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300846' AND zone_city_name = '浜松市南区' AND zone_street_name = '白羽町' AND zone_street_name_romaji = 'Shirowacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350023' AND zone_city_name = '浜松市南区' AND zone_street_name = '新貝町' AND zone_street_name_romaji = 'Shingaicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300817' AND zone_city_name = '浜松市南区' AND zone_street_name = '頭陀寺町' AND zone_street_name_romaji = 'Zudajicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350035' AND zone_city_name = '浜松市南区' AND zone_street_name = '西伝寺町' AND zone_street_name_romaji = 'Seidenjicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328062' AND zone_city_name = '浜松市南区' AND zone_street_name = '増楽町' AND zone_street_name_romaji = 'Zoracho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328065' AND zone_city_name = '浜松市南区' AND zone_street_name = '高塚町' AND zone_street_name_romaji = 'Takatsukacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328054' AND zone_city_name = '浜松市南区' AND zone_street_name = '田尻町' AND zone_street_name_romaji = 'Tajiricho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300827' AND zone_city_name = '浜松市南区' AND zone_street_name = '立野町' AND zone_street_name_romaji = 'Tatenocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328057' AND zone_city_name = '浜松市南区' AND zone_street_name = '堤町' AND zone_street_name_romaji = 'Tsutsumicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300815' AND zone_city_name = '浜松市南区' AND zone_street_name = '都盛町' AND zone_street_name_romaji = 'Tsumoricho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350022' AND zone_city_name = '浜松市南区' AND zone_street_name = '鶴見町' AND zone_street_name_romaji = 'Tsurumicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300841' AND zone_city_name = '浜松市南区' AND zone_street_name = '寺脇町' AND zone_street_name_romaji = 'Terawakicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300824' AND zone_city_name = '浜松市南区' AND zone_street_name = '富屋町' AND zone_street_name_romaji = 'Tomiyacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300845' AND zone_city_name = '浜松市南区' AND zone_street_name = '中田島町' AND zone_street_name_romaji = 'Nakatajimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300832' AND zone_city_name = '浜松市南区' AND zone_street_name = '長田町' AND zone_street_name_romaji = 'Nagatacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300837' AND zone_city_name = '浜松市南区' AND zone_street_name = '西島町' AND zone_street_name_romaji = 'Nishijimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300821' AND zone_city_name = '浜松市南区' AND zone_street_name = '西町' AND zone_street_name_romaji = 'Nishimachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328058' AND zone_city_name = '浜松市南区' AND zone_street_name = '新橋町' AND zone_street_name_romaji = 'Nippashicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300838' AND zone_city_name = '浜松市南区' AND zone_street_name = '鼡野町' AND zone_street_name_romaji = 'Nezuminocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328053' AND zone_city_name = '浜松市南区' AND zone_street_name = '法枝町' AND zone_street_name_romaji = 'Noriedacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300822' AND zone_city_name = '浜松市南区' AND zone_street_name = '東町' AND zone_street_name_romaji = 'Higashimachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328052' AND zone_city_name = '浜松市南区' AND zone_street_name = '東若林町' AND zone_street_name_romaji = 'Higashiwakabayashicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300836' AND zone_city_name = '浜松市南区' AND zone_street_name = '福島町' AND zone_street_name_romaji = 'Fukushimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300843' AND zone_city_name = '浜松市南区' AND zone_street_name = '福塚町' AND zone_street_name_romaji = 'Fukuzukacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350032' AND zone_city_name = '浜松市南区' AND zone_street_name = '古川町' AND zone_street_name_romaji = 'Furukawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300813' AND zone_city_name = '浜松市南区' AND zone_street_name = '芳川町' AND zone_street_name_romaji = 'Hogawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300812' AND zone_city_name = '浜松市南区' AND zone_street_name = '本郷町' AND zone_street_name_romaji = 'Hongocho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300834' AND zone_city_name = '浜松市南区' AND zone_street_name = '松島町' AND zone_street_name_romaji = 'Matsushimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300853' AND zone_city_name = '浜松市南区' AND zone_street_name = '三島町' AND zone_street_name_romaji = 'Mishimacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350034' AND zone_city_name = '浜松市南区' AND zone_street_name = '安松町' AND zone_street_name_romaji = 'Yasumatsucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300855' AND zone_city_name = '浜松市南区' AND zone_street_name = '楊子町' AND zone_street_name_romaji = 'Yozucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328056' AND zone_city_name = '浜松市南区' AND zone_street_name = '米津町' AND zone_street_name_romaji = 'Yonezucho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328051' AND zone_city_name = '浜松市南区' AND zone_street_name = '若林町' AND zone_street_name_romaji = 'Wakabayashicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4350036' AND zone_city_name = '浜松市南区' AND zone_street_name = '渡瀬町' AND zone_street_name_romaji = 'Watasecho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4320000' AND zone_city_name = '浜松市北区' AND zone_street_name = '' AND zone_street_name_romaji = '';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312212' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町井伊谷' AND zone_street_name_romaji = 'Inasacho Iinoya';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312205' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町伊平' AND zone_street_name_romaji = 'Inasacho Idaira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312224' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町奥山' AND zone_street_name_romaji = 'Inasachokuyama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312213' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町金指' AND zone_street_name_romaji = 'Inasacho Kanasashi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312225' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町狩宿' AND zone_street_name_romaji = 'Inasacho Karishuku';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312202' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町川名' AND zone_street_name_romaji = 'Inasacho Kawana';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312222' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町黒渕' AND zone_street_name_romaji = 'Inasacho Kurobuchi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312537' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町渋川' AND zone_street_name_romaji = 'Inasacho Shibukawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312533' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町四方浄' AND zone_street_name_romaji = 'Inasacho Shihojo';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312215' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町白岩' AND zone_street_name_romaji = 'Inasacho Shiraiwa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312536' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町田沢' AND zone_street_name_romaji = 'Inasacho Tazawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312221' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町田畑' AND zone_street_name_romaji = 'Inasacho Tabatake';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312223' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町栃窪' AND zone_street_name_romaji = 'Inasacho Tochikubo';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312204' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町兎荷' AND zone_street_name_romaji = 'Inasacho Tokka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312532' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町西久留女木' AND zone_street_name_romaji = 'Inasacho Nishikurumeki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312206' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町西黒田' AND zone_street_name_romaji = 'Inasacho Nishikuroda';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312211' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町花平' AND zone_street_name_romaji = 'Inasacho Hanadaira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312531' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町東久留女木' AND zone_street_name_romaji = 'Inasacho Higashikurumeki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312201' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町東久留女木' AND zone_street_name_romaji = 'Inasacho Higashikurumeki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312207' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町東黒田' AND zone_street_name_romaji = 'Inasacho Higashikuroda';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312534' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町別所' AND zone_street_name_romaji = 'Inasacho Besshiyo';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312535' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町的場' AND zone_street_name_romaji = 'Inasacho Matoba';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312203' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町三岳' AND zone_street_name_romaji = 'Inasacho Mitake';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312226' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町谷沢' AND zone_street_name_romaji = 'Inasacho Yazawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312214' AND zone_city_name = '浜松市北区' AND zone_street_name = '引佐町横尾' AND zone_street_name_romaji = 'Inasacho Yoko';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338102' AND zone_city_name = '浜松市北区' AND zone_street_name = '大原町' AND zone_street_name_romaji = 'Oharacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312216' AND zone_city_name = '浜松市北区' AND zone_street_name = '神宮寺町' AND zone_street_name_romaji = 'Jingujicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312103' AND zone_city_name = '浜松市北区' AND zone_street_name = '新都田' AND zone_street_name_romaji = 'Shinmiyakoda';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312101' AND zone_city_name = '浜松市北区' AND zone_street_name = '滝沢町' AND zone_street_name_romaji = 'Takisawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338103' AND zone_city_name = '浜松市北区' AND zone_street_name = '豊岡町' AND zone_street_name_romaji = 'Toyokacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338108' AND zone_city_name = '浜松市北区' AND zone_street_name = '根洗町' AND zone_street_name_romaji = 'Nearaicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338112' AND zone_city_name = '浜松市北区' AND zone_street_name = '初生町' AND zone_street_name_romaji = 'Hatsuoicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338104' AND zone_city_name = '浜松市北区' AND zone_street_name = '東三方町' AND zone_street_name_romaji = 'Higashimikatacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311301' AND zone_city_name = '浜松市北区' AND zone_street_name = '細江町小野' AND zone_street_name_romaji = 'Hosoechono';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311305' AND zone_city_name = '浜松市北区' AND zone_street_name = '細江町気賀' AND zone_street_name_romaji = 'Hosoecho Kiga';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311304' AND zone_city_name = '浜松市北区' AND zone_street_name = '細江町中川' AND zone_street_name_romaji = 'Hosoecho Nakagawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311302' AND zone_city_name = '浜松市北区' AND zone_street_name = '細江町広岡' AND zone_street_name_romaji = 'Hosoecho Hiroka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311303' AND zone_city_name = '浜松市北区' AND zone_street_name = '細江町三和' AND zone_street_name_romaji = 'Hosoecho Miwa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338105' AND zone_city_name = '浜松市北区' AND zone_street_name = '三方原町' AND zone_street_name_romaji = 'Mikataharacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311404' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町宇志' AND zone_street_name_romaji = 'Mikkabicho Ushi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311403' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町大崎' AND zone_street_name_romaji = 'Mikkabicho Osaki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311407' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町大谷' AND zone_street_name_romaji = 'Mikkabicho Oya';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311415' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町岡本' AND zone_street_name_romaji = 'Mikkabichokamoto';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311425' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町上尾奈' AND zone_street_name_romaji = 'Mikkabicho Kamiona';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311406' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町駒場' AND zone_street_name_romaji = 'Mikkabicho Komaba';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311401' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町佐久米' AND zone_street_name_romaji = 'Mikkabicho Sakume';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311424' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町下尾奈' AND zone_street_name_romaji = 'Mikkabicho Shimona';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311412' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町只木' AND zone_street_name_romaji = 'Mikkabicho Tadaki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311402' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町都筑' AND zone_street_name_romaji = 'Mikkabicho Tsuzuki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311405' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町津々崎' AND zone_street_name_romaji = 'Mikkabicho Tsuzusaki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311416' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町釣' AND zone_street_name_romaji = 'Mikkabicho Tsuri';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311423' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町鵺代' AND zone_street_name_romaji = 'Mikkabicho Nueshiro';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311422' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町日比沢' AND zone_street_name_romaji = 'Mikkabicho Hibisawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311417' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町平山' AND zone_street_name_romaji = 'Mikkabicho Hirayama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311411' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町福長' AND zone_street_name_romaji = 'Mikkabicho Fukunaga';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311421' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町本坂' AND zone_street_name_romaji = 'Mikkabicho Honzaka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311413' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町摩訶耶' AND zone_street_name_romaji = 'Mikkabicho Makaya';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4311414' AND zone_city_name = '浜松市北区' AND zone_street_name = '三ヶ日町三ヶ日' AND zone_street_name_romaji = 'Mikkabicho Mikkabi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312102' AND zone_city_name = '浜松市北区' AND zone_street_name = '都田町' AND zone_street_name_romaji = 'Miyakodacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4338101' AND zone_city_name = '浜松市北区' AND zone_street_name = '三幸町' AND zone_street_name_romaji = 'Miyukicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4312104' AND zone_city_name = '浜松市北区' AND zone_street_name = '鷲沢町' AND zone_street_name_romaji = 'Washizawacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340000' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '' AND zone_street_name_romaji = '';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340027' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '油一色' AND zone_street_name_romaji = 'Aburaishiki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340044' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '内野' AND zone_street_name_romaji = 'Uchino';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340045' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '内野台' AND zone_street_name_romaji = 'Uchinodai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340005' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '大平' AND zone_street_name_romaji = 'Oidaira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340002' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '尾野' AND zone_street_name_romaji = 'Ono';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340015' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '於呂' AND zone_street_name_romaji = 'Oro';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340011' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '上島' AND zone_street_name_romaji = 'Kamijima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340028' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '上善地' AND zone_street_name_romaji = 'Kamizenji';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340038' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '貴布祢' AND zone_street_name_romaji = 'Kibune';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340031' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '小林' AND zone_street_name_romaji = 'Kobayashi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340042' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '小松' AND zone_street_name_romaji = 'Komatsu';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340003' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '新原' AND zone_street_name_romaji = 'Shinpara';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340025' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '善地' AND zone_street_name_romaji = 'Zenji';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340046' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '染地台' AND zone_street_name_romaji = 'Somejidai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340023' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '高薗' AND zone_street_name_romaji = 'Takasono';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340034' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '高畑' AND zone_street_name_romaji = 'Takabatake';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340035' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '寺島' AND zone_street_name_romaji = 'Terajima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340032' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '道本' AND zone_street_name_romaji = 'Dohon';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340017' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '豊保' AND zone_street_name_romaji = 'Toyoyasu';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340013' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '永島' AND zone_street_name_romaji = 'Nagashima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340043' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '中条' AND zone_street_name_romaji = 'Nakajo';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340012' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '中瀬' AND zone_street_name_romaji = 'Nakaze';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340029' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '新野' AND zone_street_name_romaji = 'Niino';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340022' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '新堀' AND zone_street_name_romaji = 'Niibori';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340018' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '西中瀬' AND zone_street_name_romaji = 'Nishinakaze';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340033' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '西美薗' AND zone_street_name_romaji = 'Nishimisono';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340037' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '沼' AND zone_street_name_romaji = 'Numa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340016' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '根堅' AND zone_street_name_romaji = 'Negata';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340007' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '灰木' AND zone_street_name_romaji = 'Hainoki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340026' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '東美薗' AND zone_street_name_romaji = 'Higashimisono';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340041' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '平口' AND zone_street_name_romaji = 'Hirakuchi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340001' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '堀谷' AND zone_street_name_romaji = 'Horiya';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340014' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '本沢合' AND zone_street_name_romaji = 'Honzawai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340004' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '宮口' AND zone_street_name_romaji = 'Miyaguchi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340021' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '八幡' AND zone_street_name_romaji = 'Yawata';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340036' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '横須賀' AND zone_street_name_romaji = 'Yokosuka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340006' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '四大地' AND zone_street_name_romaji = 'Yondaichi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4340024' AND zone_city_name = '浜松市浜北区' AND zone_street_name = '竜南' AND zone_street_name_romaji = 'Ryunan';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4320000' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '' AND zone_street_name_romaji = '';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313425' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '青谷' AND zone_street_name_romaji = 'Aoya';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313535' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '芦窪' AND zone_street_name_romaji = 'Ashikubo';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313536' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '阿寺' AND zone_street_name_romaji = 'Atera';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313428' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '石神' AND zone_street_name_romaji = 'Ishigami';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313762' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '伊砂' AND zone_street_name_romaji = 'Isuka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313755' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '大川' AND zone_street_name_romaji = 'Okawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313642' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '大栗安' AND zone_street_name_romaji = 'Oguriyasu';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313305' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '大谷' AND zone_street_name_romaji = 'Oya';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313752' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '小川' AND zone_street_name_romaji = 'Ogawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313427' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '上野' AND zone_street_name_romaji = 'Kamino';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313643' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '神沢' AND zone_street_name_romaji = 'Kanzawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313641' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '熊' AND zone_street_name_romaji = 'Kuma';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313753' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久' AND zone_street_name_romaji = 'Saku';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4314111' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町相月' AND zone_street_name_romaji = 'Sakumachoaizuki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313906' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町浦川' AND zone_street_name_romaji = 'Sakumachourakawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313902' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町大井' AND zone_street_name_romaji = 'Sakumachooi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4314112' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町奥領家' AND zone_street_name_romaji = 'Sakumachookuryoke';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313903' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町上平山' AND zone_street_name_romaji = 'Sakumachokamihirayama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313907' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町川合' AND zone_street_name_romaji = 'Sakumachokawai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313901' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町佐久間' AND zone_street_name_romaji = 'Sakumachosakuma';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313904' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町戸口' AND zone_street_name_romaji = 'Sakumachotoguchi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313908' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町中部' AND zone_street_name_romaji = 'Sakumachonakabe';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313905' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '佐久間町半場' AND zone_street_name_romaji = 'Sakumachohanba';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313304' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '次郎八新田' AND zone_street_name_romaji = 'Jirohachishinden';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313754' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '相津' AND zone_street_name_romaji = 'Sozu';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313302' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '只来' AND zone_street_name_romaji = 'Tadarai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313804' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '龍山町大嶺' AND zone_street_name_romaji = 'Tatsuyamachoomine';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313802' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '龍山町下平山' AND zone_street_name_romaji = 'Tatsuyamachoshimohirayama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313801' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '龍山町瀬尻' AND zone_street_name_romaji = 'Tatsuyamachosejiri';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313803' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '龍山町戸倉' AND zone_street_name_romaji = 'Tatsuyamachotokura';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313763' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '月' AND zone_street_name_romaji = 'Tsuki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313533' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '長沢' AND zone_street_name_romaji = 'Nagasawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313761' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '西雲名' AND zone_street_name_romaji = 'Nishiunna';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313532' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '西藤平' AND zone_street_name_romaji = 'Nishifujidaira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370617' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町筏戸大上' AND zone_street_name_romaji = 'Harunochoikandookami';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370621' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町砂川' AND zone_street_name_romaji = 'Harunochoisagawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370615' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町石打松下' AND zone_street_name_romaji = 'Harunochoishiuchimatsushita';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370607' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町石切' AND zone_street_name_romaji = 'Harunochoishikiri';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370624' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町和泉平' AND zone_street_name_romaji = 'Harunochoizumidaira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370622' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町大時' AND zone_street_name_romaji = 'Harunochootoki';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370608' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町小俣京丸' AND zone_street_name_romaji = 'Harunochoomatakyomaru';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370601' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町川上' AND zone_street_name_romaji = 'Harunochokawakami';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370623' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町胡桃平' AND zone_street_name_romaji = 'Harunochokurumidaira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370605' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町気田' AND zone_street_name_romaji = 'Harunochoketa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370618' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町越木平' AND zone_street_name_romaji = 'Harunochokoshikidaira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370603' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町五和' AND zone_street_name_romaji = 'Harunochogowa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370602' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町杉' AND zone_street_name_romaji = 'Harunochosugi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370616' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町田黒' AND zone_street_name_romaji = 'Harunochotaguro';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370611' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町田河内' AND zone_street_name_romaji = 'Harunochotagochi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370614' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町長蔵寺' AND zone_street_name_romaji = 'Harunochochozoji';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370606' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町豊岡' AND zone_street_name_romaji = 'Harunochotoyoka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370612' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町花島' AND zone_street_name_romaji = 'Harunochohanajima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370625' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町堀之内' AND zone_street_name_romaji = 'Harunochohorinochi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370613' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町牧野' AND zone_street_name_romaji = 'Harunochomakino';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370604' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町宮川' AND zone_street_name_romaji = 'Harunochomiyagawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4370626' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '春野町領家' AND zone_street_name_romaji = 'Harunochoryoke';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313421' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '日明' AND zone_street_name_romaji = 'Hiari';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313751' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '東雲名' AND zone_street_name_romaji = 'Higashiunna';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313531' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '東藤平' AND zone_street_name_romaji = 'Higashifujidaira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313311' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '二俣町阿蔵' AND zone_street_name_romaji = 'Futamatachoakura';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313315' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '二俣町大園' AND zone_street_name_romaji = 'Futamatachoosono';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313313' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '二俣町鹿島' AND zone_street_name_romaji = 'Futamatachokajima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313314' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '二俣町二俣' AND zone_street_name_romaji = 'Futamatachofutamata';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313312' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '二俣町南鹿島' AND zone_street_name_romaji = 'Futamatachominamikajima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313534' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '懐山' AND zone_street_name_romaji = 'Futokoroyama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313306' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '船明' AND zone_street_name_romaji = 'Funagira';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4314101' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '水窪町奥領家' AND zone_street_name_romaji = 'Misakubochookuryoke';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4314102' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '水窪町地頭方' AND zone_street_name_romaji = 'Misakubochojitogata';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4314103' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '水窪町山住' AND zone_street_name_romaji = 'Misakubochoyamazumi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313422' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '米沢' AND zone_street_name_romaji = 'Minazawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313303' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '山東' AND zone_street_name_romaji = 'Yamahigashi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313756' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '谷山' AND zone_street_name_romaji = 'Yayama';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313301' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '横川' AND zone_street_name_romaji = 'Yokokawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313764' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '横山町' AND zone_street_name_romaji = 'Yokoyamacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313426' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '両島' AND zone_street_name_romaji = 'Ryoshima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313424' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '緑恵台' AND zone_street_name_romaji = 'Ryokukeidai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4313423' AND zone_city_name = '浜松市天竜区' AND zone_street_name = '渡ケ島' AND zone_street_name_romaji = 'Watagashima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4110917' AND zone_city_name = '駿東郡清水町' AND zone_street_name = '徳倉（上徳倉、下徳倉、外原）' AND zone_street_name_romaji = 'Tokura(kamitokura, shimotokura, sotobara)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '7900941' AND zone_city_name = '松山市' AND zone_street_name = '和泉南' AND zone_street_name_romaji = 'Izumiminami';
DELETE FROM zones_to_post_code_jp WHERE post_code = '7900038' AND zone_city_name = '松山市' AND zone_street_name = '和泉北' AND zone_street_name_romaji = 'Izumikita';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8700172' AND zone_city_name = '大分市' AND zone_street_name = '新明治' AND zone_street_name_romaji = 'Shinmeiji';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8701174' AND zone_city_name = '大分市' AND zone_street_name = '萌葱台' AND zone_street_name_romaji = 'Moegidai';
DELETE FROM zones_to_post_code_jp WHERE post_code = '9140078' AND zone_city_name = '敦賀市' AND zone_street_name = '桜町' AND zone_street_name_romaji = 'Sakuracho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4300854' AND zone_city_name = '浜松市中央区' AND zone_street_name = '瓜内町' AND zone_street_name_romaji = 'Uriuchicho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4328053' AND zone_city_name = '浜松市中央区' AND zone_street_name = '法枝町' AND zone_street_name_romaji = 'Noriedacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5960833' AND zone_city_name = '岸和田市' AND zone_street_name = '神須屋町' AND zone_street_name_romaji = 'Kozuyacho';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5550011' AND zone_city_name = '大阪市西淀川区' AND zone_street_name = '竹島' AND zone_street_name_romaji = 'Takeshima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5550041' AND zone_city_name = '大阪市西淀川区' AND zone_street_name = '中島' AND zone_street_name_romaji = 'Nakashima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5550042' AND zone_city_name = '大阪市西淀川区' AND zone_street_name = '西島' AND zone_street_name_romaji = 'Nishishima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5550033' AND zone_city_name = '大阪市西淀川区' AND zone_street_name = '姫島' AND zone_street_name_romaji = 'Himeshima';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8740836' AND zone_city_name = '別府市' AND zone_street_name = '東荘園' AND zone_street_name_romaji = 'Higashisoen';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8960052' AND zone_city_name = 'いちき串木野市' AND zone_street_name = '上名' AND zone_street_name_romaji = 'Kanmyo';
DELETE FROM zones_to_post_code_jp WHERE post_code = '0660076' AND zone_city_name = '千歳市' AND zone_street_name = 'あずさ' AND zone_street_name_romaji = 'Azusa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630790' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（地階・階層不明）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(chikai.kaisofumei)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630701' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(1kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630702' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（２階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(2kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630703' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（３階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(3kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630704' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（４階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(4kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630705' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（５階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(5kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630706' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（６階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(6kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630707' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（７階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(7kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630708' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（８階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(8kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630709' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（９階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(9kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630710' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１０階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(10kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630711' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１１階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(11kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630712' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１２階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(12kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630713' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１３階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(13kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630714' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１４階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(14kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630715' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１５階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(15kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630716' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１６階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(16kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630717' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１７階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(17kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630718' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１８階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(18kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630719' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（１９階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(19kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630720' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（２０階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(20kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630721' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（２１階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(21kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630722' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（２２階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(22kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630723' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（２３階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(23kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630724' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（２４階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(24kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630725' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（２５階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(25kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '1630726' AND zone_city_name = '新宿区' AND zone_street_name = '西新宿小田急第一生命ビル（２６階）' AND zone_street_name_romaji = 'Nishishinjiyukuodakiyudaiichiseimeibiru(26kai)';
DELETE FROM zones_to_post_code_jp WHERE post_code = '8111124' AND zone_city_name = '福岡市早良区' AND zone_street_name = '金武' AND zone_street_name_romaji = 'Kanatake';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5700043' AND zone_city_name = '守口市' AND zone_street_name = '高瀬旧大枝' AND zone_street_name_romaji = 'Takasekyu Oeda';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5700043' AND zone_city_name = '守口市' AND zone_street_name = '高瀬旧世木' AND zone_street_name_romaji = 'Takasekyu Segi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5700043' AND zone_city_name = '守口市' AND zone_street_name = '高瀬旧馬場' AND zone_street_name_romaji = 'Takasekyu Baba';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5700043' AND zone_city_name = '守口市' AND zone_street_name = '南寺方東通' AND zone_street_name_romaji = 'Minamiterakatahigashidori';
DELETE FROM zones_to_post_code_jp WHERE post_code = '9230995' AND zone_city_name = '小松市' AND zone_street_name = '安宅新町' AND zone_street_name_romaji = 'Atakashinmachi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '7315116' AND zone_city_name = '広島市佐伯区' AND zone_street_name = '五日市町寺田' AND zone_street_name_romaji = 'Itsukaichicho Terada';
DELETE FROM zones_to_post_code_jp WHERE post_code = '7315115' AND zone_city_name = '広島市佐伯区' AND zone_street_name = '五日市町中地' AND zone_street_name_romaji = 'Itsukaichicho Nakaji';
DELETE FROM zones_to_post_code_jp WHERE post_code = '7315116' AND zone_city_name = '広島市佐伯区' AND zone_street_name = '八幡' AND zone_street_name_romaji = 'Yahata';
DELETE FROM zones_to_post_code_jp WHERE post_code = '7315115' AND zone_city_name = '広島市佐伯区' AND zone_street_name = '八幡東' AND zone_street_name_romaji = 'Yahatahigashi';
DELETE FROM zones_to_post_code_jp WHERE post_code = '9895126' AND zone_city_name = '栗原市' AND zone_street_name = '金成鍔ノ瓦' AND zone_street_name_romaji = 'Kannari Tsubanokawara';
DELETE FROM zones_to_post_code_jp WHERE post_code = '3550215' AND zone_city_name = '比企郡嵐山町' AND zone_street_name = '平沢' AND zone_street_name_romaji = 'Hirasawa';
DELETE FROM zones_to_post_code_jp WHERE post_code = '5013942' AND zone_city_name = '関市' AND zone_street_name = '希望ケ丘' AND zone_street_name_romaji = 'Kibogaoka';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4250041' AND zone_city_name = '焼津市' AND zone_street_name = '石津' AND zone_street_name_romaji = 'Ishizu';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4250034' AND zone_city_name = '焼津市' AND zone_street_name = '与惣次' AND zone_street_name_romaji = 'Yosoji';
DELETE FROM zones_to_post_code_jp WHERE post_code = '4440312' AND zone_city_name = '西尾市' AND zone_street_name = '国森町' AND zone_street_name_romaji = 'Kunimoricho';
